version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: crs-postgres
    environment:
      POSTGRES_USER: mavenUser
      POSTGRES_PASSWORD: maven1234
      POSTGRES_DB: courseRegTestDb
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: crs-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data:

  # docker exec -it crs-postgres psql -U mavenUser -d courseRegTestDb

