name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '11'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean verify

    # (Optional but useful) always keep a JUnit HTML report as an artifact
    - name: Generate Surefire report
      if: ${{ always() }}
      run: mvn surefire-report:report-only

    - name: Archive Surefire report
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: surefire-report
        path: '**/target/site/surefire-report.html'
